create extension if not exists "pgcrypto";

create table public.users (
  id uuid primary key references auth.users (id),
  role text not null check (role in ('admin', 'operator')),
  full_name text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.parking_lots (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  address text,
  rows integer not null check (rows > 0),
  columns integer not null check (columns > 0),
  created_at timestamptz not null default now()
);

create table public.parking_spots (
  id uuid primary key default gen_random_uuid(),
  parking_lot_id uuid not null references public.parking_lots (id),
  spot_number text not null,
  vehicle_type text,
  status text not null default 'available'
    check (status in ('available', 'occupied', 'out_of_service')),
  out_of_service_reason text,
  created_at timestamptz not null default now(),
  unique (parking_lot_id, spot_number)
);

create index parking_spots_status_idx on public.parking_spots (status);

create table public.vehicles (
  id uuid primary key default gen_random_uuid(),
  plate text not null check (plate = upper(regexp_replace(plate, '\s+', '', 'g'))),
  vehicle_type text not null,
  created_at timestamptz not null default now(),
  unique (plate)
);

create table public.rates (
  id uuid primary key default gen_random_uuid(),
  vehicle_type text not null,
  hourly_price numeric(10, 2) not null check (hourly_price > 0),
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create unique index one_active_rate_per_vehicle_type
  on public.rates (vehicle_type)
  where is_active = true;

create table public.parking_sessions (
  id uuid primary key default gen_random_uuid(),
  vehicle_id uuid not null references public.vehicles (id),
  spot_id uuid not null references public.parking_spots (id),
  status text not null default 'active'
    check (status in ('active', 'pending_payment', 'completed', 'cancelled')),
  entry_time timestamptz not null default now(),
  exit_time timestamptz,
  rate_snapshot_id uuid not null references public.rates (id),
  rate_snapshot_price numeric(10, 2) not null check (rate_snapshot_price > 0),
  billable_hours integer check (billable_hours is null or billable_hours > 0),
  total_amount numeric(10, 2) check (total_amount is null or total_amount > 0),
  created_by uuid references public.users (id),
  closed_by uuid references public.users (id),
  created_at timestamptz not null default now()
);

create unique index one_active_session_per_vehicle
  on public.parking_sessions (vehicle_id)
  where status = 'active';

create unique index one_active_session_per_spot
  on public.parking_sessions (spot_id)
  where status = 'active';

create table public.payments (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.parking_sessions (id),
  amount numeric(10, 2) not null check (amount > 0),
  method text,
  status text not null default 'pending' check (status in ('pending', 'paid')),
  paid_by uuid references public.users (id),
  created_at timestamptz not null default now(),
  unique (session_id)
);

create table public.invoices (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null unique references public.parking_sessions (id),
  receipt_number bigint generated by default as identity not null unique,
  snapshot jsonb not null,
  generated_at timestamptz not null default now()
);

create table public.audit_logs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users (id),
  action text not null,
  entity_type text not null,
  entity_id uuid,
  metadata jsonb,
  created_at timestamptz not null default now()
);

create index audit_logs_entity_idx on public.audit_logs (entity_type, entity_id);
create index audit_logs_created_at_idx on public.audit_logs (created_at);

create schema if not exists private;
revoke all on schema private from public;
grant usage on schema private to anon, authenticated;

create function private.is_active_staff()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.users
    where id = auth.uid()
      and is_active = true
  );
$$;

create function private.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.users
    where id = auth.uid()
      and role = 'admin'
      and is_active = true
  );
$$;

grant execute on function private.is_active_staff() to anon, authenticated;
grant execute on function private.is_admin() to anon, authenticated;

alter table public.users enable row level security;
alter table public.parking_lots enable row level security;
alter table public.parking_spots enable row level security;
alter table public.vehicles enable row level security;
alter table public.rates enable row level security;
alter table public.parking_sessions enable row level security;
alter table public.payments enable row level security;
alter table public.invoices enable row level security;
alter table public.audit_logs enable row level security;

create policy "users_read_own_or_admin"
  on public.users for select to authenticated
  using (id = auth.uid() or private.is_admin());
create policy "users_admin_write"
  on public.users for all to authenticated
  using (private.is_admin())
  with check (private.is_admin());

create policy "parking_lots_staff_read"
  on public.parking_lots for select to authenticated
  using (private.is_active_staff());
create policy "parking_lots_admin_write"
  on public.parking_lots for all to authenticated
  using (private.is_admin())
  with check (private.is_admin());

create policy "parking_spots_staff_read"
  on public.parking_spots for select to authenticated
  using (private.is_active_staff());
create policy "parking_spots_admin_write"
  on public.parking_spots for all to authenticated
  using (private.is_admin())
  with check (private.is_admin());

create policy "vehicles_staff_read"
  on public.vehicles for select to authenticated
  using (private.is_active_staff());
create policy "vehicles_staff_insert"
  on public.vehicles for insert to authenticated
  with check (private.is_active_staff());

create policy "rates_staff_read"
  on public.rates for select to authenticated
  using (private.is_active_staff());
create policy "rates_admin_write"
  on public.rates for all to authenticated
  using (private.is_admin())
  with check (private.is_admin());

create policy "sessions_staff_read"
  on public.parking_sessions for select to authenticated
  using (private.is_active_staff());
create policy "sessions_staff_insert"
  on public.parking_sessions for insert to authenticated
  with check (private.is_active_staff());
create policy "sessions_staff_update_nonterminal"
  on public.parking_sessions for update to authenticated
  using (private.is_active_staff() and status in ('active', 'pending_payment'))
  with check (private.is_active_staff());

create policy "payments_staff_read"
  on public.payments for select to authenticated
  using (private.is_active_staff());
create policy "payments_staff_insert"
  on public.payments for insert to authenticated
  with check (private.is_active_staff());
create policy "payments_staff_update"
  on public.payments for update to authenticated
  using (private.is_active_staff())
  with check (private.is_active_staff());

create policy "invoices_staff_read"
  on public.invoices for select to authenticated
  using (private.is_active_staff());
create policy "invoices_staff_insert"
  on public.invoices for insert to authenticated
  with check (private.is_active_staff());

create policy "audit_logs_admin_read"
  on public.audit_logs for select to authenticated
  using (private.is_admin());
create policy "audit_logs_admin_write"
  on public.audit_logs for all to authenticated
  using (private.is_admin())
  with check (private.is_admin());
